"""update role access permission fields

Revision ID: 8cf512941921
Revises: ce03310e9934
Create Date: 2025-11-03 22:32:58.762734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf512941921'
down_revision: Union[str, Sequence[str], None] = 'ce03310e9934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_access', sa.Column('read_roles_permission', sa.Boolean(), nullable=True))
    op.add_column('role_access', sa.Column('update_roles_permission', sa.Boolean(), nullable=True))
    op.drop_column('role_access', 'update_permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_access', sa.Column('update_permission', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('role_access', 'update_roles_permission')
    op.drop_column('role_access', 'read_roles_permission')
    # ### end Alembic commands ###
