"""user update is_active to boolean

Revision ID: ce03310e9934
Revises: e54ba80471d9
Create Date: 2025-11-03 21:43:30.476899

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce03310e9934"
down_revision: str | Sequence[str] | None = "e54ba80471d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="is_active::boolean",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active",
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
