"""user roles

Revision ID: f39262bb11e8
Revises: f641e740d228
Create Date: 2025-11-03 19:32:02.692010

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f39262bb11e8"
down_revision: str | Sequence[str] | None = "f641e740d228"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("roles",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table("role_access",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("role_id", sa.Integer(), nullable=False),
    sa.Column("add_user_permission", sa.Boolean(), nullable=True),
    sa.Column("read_users_permission", sa.Boolean(), nullable=True),
    sa.Column("update_users_permission", sa.Boolean(), nullable=True),
    sa.Column("delete_users_permission", sa.Boolean(), nullable=True),
    sa.Column("update_permission", sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_role_access_id"), "role_access", ["id"], unique=False)
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["id"])
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", postgresql.ENUM("ADMIN", "USER", name="user_role_enum"), autoincrement=False, nullable=True))
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("ix_role_access_id"), table_name="role_access")
    op.drop_table("role_access")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
