"""user model

Revision ID: f641e740d228
Revises: 
Create Date: 2025-11-02 18:53:34.126952

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f641e740d228"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("full_name", sa.String(), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("registered_date", sa.DateTime(), nullable=True),
    sa.Column("hashed_password", sa.String(), nullable=False),
    sa.Column("role", postgresql.ENUM("ADMIN", "USER", name="user_role_enum"), nullable=True),
    sa.Column("active", sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("username")
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
